### PR TITLE
Files filtering and stay alive

### PR DESCRIPTION
**Pull request by JeanBilheux**
This pull request implemented 2 new features, the **files filtering** and the **stay alive** flag.

**files filtering**
By passing a dictionary (key=message to display, value=search engine) it's possible to narrow down the list of files displayed

```
fsel= ipywe.fileselector.FileSelectorPanel(instruction='select file', start_dir='.', 
                                           filter={'notebooks': ['*.ipynb'],'csv': ['*.csv']})
fsel.show()
```
When passing a filter dictionary, the program will automatically add the 'All':['*.*'] element to the dictionary

**stay alive**
when the flag is passed, the application won't be removed once the user click **Select**

### CODE REVIEW

**Comment by yxqd** [comment]
I changed the signature of filtering a bit

```
fsel= ipywe.fileselector.FileSelectorPanel(
    instruction='select file', start_dir='.', 
    filters={'notebooks': ['*.ipynb'],'csv': ['*.csv']}, default_filter="notebooks")
```
When passing a filter dictionary, the program will automatically add the 'All':['*.*'] element to the dictionary

**Comment by yxqd** [comment]
Now working on rearranging the layout a bit

**Comment by yxqd** [comment]
I was looking at mac's file open dialog. It does not exactly have a "filter" widget, but it has a "search" widget on the top right corner of the panel, on top of the list of entries. That is why I put it up there.

**Comment by yxqd** [comment]
I finished all my changes for now. Please give it a try

**Comment by JeanBilheux** [comment]
ok. I'm checking

**Comment by JeanBilheux** [comment]
I changed my mind... I really like it there. I'm wondering now about the two other buttons **enter directory** and **select**. Those always confused users. We need to find them a better name or to move them apart (like before for example)

**Pull request merged**
