### PR TITLE
Fix bug when using search toolbox

### PR DESCRIPTION
**Pull request by JeanBilheux**
search_bug

### CODE REVIEW

**Comment by yxqd** [comment]
Could you please clean the output before check in the notebook?

**Comment by JeanBilheux** [comment]
Sorry Jiao. I guess I did it again  :-)
just fixed it

**Comment by yxqd** [comment]
Thanks!

**Comment by yxqd** [comment]
So the previous behavior was

* User input a str in the search box, hit Enter, see a filtered list of entries
* User input empty str in the search box, do NOT hit Enter, select a directory, click "Enter directory"
* User still see a filtered list of entries
* The bug is that the search string is "remembered" and still in use after user cleared it

The new behavior will be
* When user clicks "Enter directory" but have not yet hit Enter key, the new directory view will show the filtered list that uses the current search string on display

**Comment by JeanBilheux** [comment]
Tested the modifications and it works. This ticket can be merged.

**Pull request merged**
