### PR TITLE
Updating the Widgets' Python Code to Python 3.X

### LINKED ISSUE #41: making this library python 3.x compatible

### PR DESCRIPTION
**Pull request by ilumsden**
Fixes #41.

In case if anyone is concerned, I used Flake8 and Python 3.6.2 to do the conversion.

### CODE REVIEW

**Comment by ilumsden** [comment]
_**DON'T merge this yet.**_ I just noticed one issue that Flake8 didn't catch. Apparently, the StringIO and cStringIO modules have been depreciated as of Python 3.0. They are used in the ImageSlider and ImageDisplay widgets, and they need to be replaced with imports of the io module.

**Comment by ilumsden** [comment]
~~**Issue:** There is an issue with the PIL statements in the ImageDisplay, ImageSlider, and ImgDataGraph widgets when they're run with Python 3.~~ Fixed by commits 5d7ab3f, 26fdb32, d893acf, and 237a5e4.

**Comment by ilumsden** [comment]
~~**Issue:** Zooming in the ImageDisplay and ImageSlider widgets is broken in Python 3 due to the changes to division.~~ Fixed by commits 5d7ab3f, 26fdb32, d893acf, and 237a5e4.

**Comment by ilumsden** [comment]
@JeanBilheux and @yxqd,

This pull request is now ready to be merged. However, before you do, I just want to warn you about something. As a result of the division changes I made, the ImageDisplay, ImageSlider, and ImgDataGraph widgets now only work with Python 2.7+ (including all versions of 3.X). This is due to the `from __future__ import division` line at the beginning of the Python scripts. The `__future__`module only works with Python 2.7+ because it was meant to add cross-compatibility between 2.7 and 3.X. Let me know if this code should be changed so that versions of Python less than 2.7 can be used.

**Comment by yxqd** [comment]
Sounds good. I don't think backward compatibility with python 2.6- is important.

**Comment by ilumsden** [comment]
I didn't think it would be, but I wanted to warn you, just in case.

**Comment by JeanBilheux** [comment]
I agree with Jiao... the future is 3.5+, we don't care about 2.6-

**Comment by yxqd** [comment]
Thanks @ilumsden. This looks great. 

I only made a minor change to fix the print syntax in test_wizard notebook.

**Pull request merged**
